insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE) values (1,'HCL',700.25);
insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE) values (2,'Infosys',950.25);
insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE) values (3,'BHEL',40.85);
insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE) values (4,'Ineuron',71.50);